#!/usr/bin/env python3
from filter import *

log(f"Démarrage. Invoqué depuis { url }")

fruit = "🍎🥝🍊🥭🍈🍑🍐🧄🍓🥦🌽🥬🥑🍉🥔🍅🥕🌶🍒🥥"
transform = "etsphroylifcugvdnmb"
cesar = str.maketrans(fruit, transform)

for line in input:
    output.write(line.translate(cesar))

log(f"Fin du traitement.")
